#!/usr/bin/env bash

set -e

# if ["$1" -eq "--all"]; then
# 	echo "Running all shell install scripts..."
# 	for f in ls *.sh; do
# 		exec $f
# 	fi
# fi

CONFIG="install.conf.json"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
