" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
filetype off

" ================ Vundle Initialization ================

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/vundles')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Color schemes
Plugin 'wellsjo/wellsokai.vim'

" Navigation
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'vim-ctrlspace/vim-ctrlspace'

" General editing improvements
Plugin 'scrooloose/nerdcommenter'
Plugin 'AndrewRadev/splitjoin.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Language-specific plugins
Plugin 'fatih/vim-go'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" ================ Turn Off Swap Files ==============

set noswapfile
set nobackup
set nowb

" ================ General Config ================

set number 		" line numbers
set ignorecase	" case-insensitive searching
set smartcase   " ...unless we type a capital

" syntax highlighting
syntax on

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" Automatically save on make (or GoBuild).
set autowrite

" Set one of the color schemes from above
colorscheme wellsokai

" Use spaces as indents when entered with tab
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

" Remove whitespace from end of lines
nnoremap <leader>w :%s/\s\+$//<CR>

" ================ Plugin Config ================

" Airline theme
let g:airline_theme='luna'

" Map NERDTree to Ctrl+n
map <C-n> :NERDTreeToggle<CR>
" Start up NERDTree if vim was opened without a specified file
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Bind CtrlP to <c-p>
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
" Have CtrlP start its search based on the directory of the current open file
let g:ctrlp_working_path_mode = 'a'

" Vim-Go configuration and key bindings
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_list_type = "quickfix"

autocmd FileType go nmap <leader>b  <Plug>(go-build)
autocmd FileType go nmap <leader>r  <Plug>(go-run)
autocmd FileType go nmap <leader>i  <Plug>(go-install)
map <C-j> :cnext<CR>
map <C-k> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

" NERDCommenter
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1
" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1
" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1

" Format JSON inline
com FmtJSON execute "%!python -m json.tool"
