############  General Settings ############
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE
export HISTFILE=~/.zhistory
export CLICOLOR=1

################ Powerlevel9k ################

DISABLE_AUTO_TITLE='true'

POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(pyenv rbenv)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

# Disable dir/git icons
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'

# POWERLEVEL9K_PROMPT_ON_NEWLINE=true
# POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

################ Antigen ################

source ~/.antigen_lnk/antigen.zsh

antigen use oh-my-zsh

# Plugins
antigen bundle git
antigen bundle brew
antigen bundle sublime
antigen bundle python
antigen bundle ruby
antigen bundle encode64

antigen bundle httpie

# Theme
# antigen bundle yous/lime
# antigen theme gianu
# antigen theme geoffgarside
antigen theme bhilburn/powerlevel9k powerlevel9k

antigen apply

################ Aliases ################

alias shidden='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder'
alias hhidden='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder'

alias em='env SHELL=/usr/local/bin/zsh emacs'
alias tn='tmux new'
alias tnd='tmux new -s devel'
alias ta='tmux attach #'
alias tad='tmux attach -t devel'

alias mysqlstart='mysql.server start'
alias mysqlstop='mysql.server stop'

############### Functions ###############

# Pass true to enable alternate characters or false to enable repeating keys.
altcharacters() {
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool $1
}

########## $PATH modifications ##########

# Path definitions are here so that OSX's path_helper doesn't ruin things.
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=${PATH}:/opt/X11/include:/opt/X11/bin

# macOS only
if [[ `uname` == 'Darwin' ]]; then
	# Include VSCode binaries on path if we have it installed.
    if [ -e /Applications/Visual\ Studio\ Code.app ]; then
        export PATH=${PATH}:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
    fi
fi

export GOPATH="$HOME/Development/godev"

############# Setup Scripts #############

# Pyenv
if [ `command -v pyenv` ]; then
	eval "$(pyenv init -)"	
fi

# Rbenv
if [ `command -v rbenv` ]; then
	eval "$(rbenv init -)"
fi

######## Load zsh scripts from zsh/ directory #######

# Source everything from the zsh folder
# for f in ~/.dotfiles/zsh/*.zsh; do
#     source $f
# done

########## Load dotfiles_local zsh configs #########

# Source a local zshrc if it exists.
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi
