export HISTSIZE=99999
export SAVEHIST=$HISTSIZE
export HISTFILE=~/.zhistory
export CLICOLOR=1

#### Antigen Stuff ####
source ~/.antigen_lnk/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle brew
antigen bundle sublime
antigen bundle python
antigen bundle ruby
antigen bundle encode64
antigen bundle httpie

# antigen bundle yous/lime
# antigen theme gianu
antigen theme geoffgarside

antigen apply

#### Aliases ####
alias shidden='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder'
alias hhidden='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder'

alias startmysql='mysql.server start'
alias em='env SHELL=/usr/local/bin/zsh emacs'

# Source everything from the zsh folder
# for f in ~/.dotfiles/zsh/*.zsh; do
#     source $f
# done

# Source a local zshrc if it exists.
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

