############  General Settings ############
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE
export HISTFILE=~/.zhistory
export CLICOLOR=1

################ Antigen ################

source ~/.antigen_lnk/antigen.zsh

antigen use oh-my-zsh

# Plugins
antigen bundle brew
antigen bundle git
antigen bundle sublime
antigen bundle python
antigen bundle ruby
antigen bundle golang
antigen bundle encode64
antigen bundle httpie

# Theme
# antigen theme geoffgarside
# antigen theme bhilburn/powerlevel9k powerlevel9k
# antigen theme af-magic

antigen apply

################ Aliases ################

if [[ `uname` == 'Darwin' ]]; then
    alias mysqlstart='mysql.server start'
    alias mysqlstop='mysql.server stop'
fi

# Tmux commands.
alias tn='tmux new'
alias tnd='tmux new -s dev'
alias ta='tmux attach #'
alias tad='tmux attach -t dev'

# Redis.
alias start-redis='redis-server /usr/local/etc/redis.conf'

############### Functions ###############

if [[ `uname` == 'Darwin' ]]; then
    # Pass true to enable alternate characters or false to enable repeating keys.
    altcharacters() {
        defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool $1
    }
fi

########## $PATH modifications ##########

# Path definitions are here so that OSX's path_helper doesn't ruin things.
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

export PATH=${PATH}:/opt/X11/include:/opt/X11/bin

# macOS only
if [[ `uname` == 'Darwin' ]]; then
	# Include VSCode binaries on path if we have it installed.
    if [ -e /Applications/Visual\ Studio\ Code.app ]; then
        export PATH=/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin:${PATH}
    fi

    # Include the Postgres binaries from the latest version of Postgres installed throug
    # Postgres.app. Prevents some inconsistencies with the Homebrew-installed tools.
    if [ -e /Applications/Postgres.app ]; then
        export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:${PATH}
    fi
fi

######## Miscallaneous Env Vars #########



############# Setup Scripts #############

# gvm
if [ -d $HOME/.gvm ]; then
    source $HOME/.gvm/scripts/gvm
fi

# pyenv
if [ `command -v pyenv` ]; then
    eval "$(pyenv init -)"
fi

# rbenv
if [ `command -v rbenv` ]; then
    eval "$(rbenv init -)"
fi

# nvm
if [ -d $HOME/.nvm ]; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
    [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
fi

# Starship
if [ `command -v starship` ]; then
    eval "$(starship init zsh)"	
fi

########## Load dotfiles_local zsh configs #########

# Source a local zshrc if it exists.
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi
